# Generated by Django 3.1.3 on 2020-12-23 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='home',
            new_name='home_page',
        ),
    ]
