# Generated by Django 3.1.3 on 2020-12-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20201223_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='media_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(default='', upload_to='')),
            ],
        ),
    ]
