# Generated by Django 3.1.3 on 2020-12-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_media_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='media_page',
            name='my_picture',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
