# Generated by Django 3.1.3 on 2020-12-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_media_page_my_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_page',
            name='category',
            field=models.TextField(default=''),
        ),
    ]
