# Generated by Django 3.1.3 on 2020-12-24 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='content',
            new_name='contact',
        ),
    ]
