# Generated by Django 3.2.6 on 2021-10-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_auto_20201224_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='github',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='media_page',
            name='cv',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='media_page',
            name='my_picture',
            field=models.URLField(default=''),
        ),
    ]
