# Generated by Django 3.2.6 on 2021-10-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_auto_20211018_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media_page',
            name='cv',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='media_page',
            name='my_picture',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
