# Generated by Django 3.2.6 on 2021-10-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_auto_20211018_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('age', models.PositiveSmallIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('address', models.TextField()),
                ('languages', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('value', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='youtube',
            field=models.URLField(default='https://youtube.come/'),
            preserve_default=False,
        ),
    ]
