# Generated by Django 3.2.6 on 2021-10-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_auto_20211018_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
