# Generated by Django 3.2.6 on 2021-10-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_auto_20211018_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
