# Generated by Django 3.2.6 on 2021-10-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_contact_twitter'),
    ]

    operations = [
        migrations.CreateModel(
            name='workExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('position', models.CharField(max_length=200)),
                ('start', models.CharField(max_length=20)),
                ('end', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
    ]
