# Generated by Django 3.2.6 on 2021-10-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_workexperience'),
    ]

    operations = [
        migrations.CreateModel(
            name='educationExp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=80)),
                ('position', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('start', models.CharField(max_length=20)),
                ('end', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='workExperience',
            new_name='workExp',
        ),
    ]
