# Generated by Django 3.2.6 on 2021-10-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_auto_20211025_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('link', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='link',
            field=models.ManyToManyField(to='Home.contactLink'),
        ),
    ]
