# Generated by Django 3.2.6 on 2021-10-25 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_alter_contact_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactlink',
            old_name='link',
            new_name='url',
        ),
    ]
