# Generated by Django 3.2.6 on 2021-10-25 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_rename_link_contactlink_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='link',
        ),
        migrations.AddField(
            model_name='contact',
            name='link0',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link0', to='Home.contactlink'),
        ),
        migrations.AddField(
            model_name='contact',
            name='link1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link1', to='Home.contactlink'),
        ),
        migrations.AddField(
            model_name='contact',
            name='link2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link2', to='Home.contactlink'),
        ),
    ]
