# Generated by Django 3.2.6 on 2021-10-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0020_contact_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media_page',
            name='cv',
            field=models.FileField(default='', upload_to='resume'),
        ),
        migrations.AlterField(
            model_name='media_page',
            name='my_picture',
            field=models.ImageField(default='', upload_to='my_picture'),
        ),
    ]
