# Generated by Django 3.2.6 on 2021-10-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0021_auto_20211026_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='duration',
            field=models.CharField(choices=[('Less than 3 months', 'Less than 3 months'), ('Between 3 and 6 months', 'Between 3 and 6 months'), ('Less than 1 year', 'Less than 1 year'), ('Between 1 and 2 years', 'Between 1 and 2 years'), ('Between 2 and 3 years', 'Between 2 and 3 years'), ('Between 3 and 4 years', 'Between 3 and 4 years'), ('Between 4 and 5 years', 'Between 4 and 5 years'), ('Between 5 and 6 years', 'Between 5 and 6 years'), ('Between 6 and 7 years', 'Between 6 and 7 years'), ('Between 7 and 8 years', 'Between 7 and 8 years'), ('Between 8 and 9 years', 'Between 8 and 9 years'), ('Between 9 and 10 years', 'Between 9 and 10 years')], default='Less than 3 months', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='media_page',
            name='cv',
            field=models.FileField(default='', upload_to='Home/media/resume'),
        ),
        migrations.AlterField(
            model_name='media_page',
            name='my_picture',
            field=models.ImageField(default='', upload_to='Home/media/my_picture'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='value',
            field=models.CharField(choices=[('Less than 3 months', 8.3), ('Between 3 and 6 months', 16.7), ('Less than 1 year', 25), ('Between 1 and 2 years', 33.3), ('Between 2 and 3 years', 41.7), ('Between 3 and 4 years', 50), ('Between 4 and 5 years', 58.3), ('Between 5 and 6 years', 66.7), ('Between 6 and 7 years', 75), ('Between 7 and 8 years', 83.3), ('Between 8 and 9 years', 91.7), ('Between 9 and 10 years', 99)], max_length=40),
        ),
    ]
