# Generated by Django 3.2.6 on 2021-10-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0022_auto_20211026_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='value',
            field=models.CharField(choices=[(8.3, 'Less than 3 months'), ('Between 3 and 6 months', 16.7), ('Less than 1 year', 25), ('Between 1 and 2 years', 33.3), ('Between 2 and 3 years', 41.7), ('Between 3 and 4 years', 50), ('Between 4 and 5 years', 58.3), ('Between 5 and 6 years', 66.7), ('Between 6 and 7 years', 75), ('Between 7 and 8 years', 83.3), ('Between 8 and 9 years', 91.7), ('Between 9 and 10 years', 99)], max_length=40),
        ),
    ]
