# Generated by Django 3.2.6 on 2021-10-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0024_alter_skill_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='value',
            field=models.CharField(choices=[('8.3', 'Less than 3 months'), ('16.7', 'Between 3 and 6 months'), ('25', 'Less than 1 year'), ('33.3', 'Between 1 and 2 years'), ('41.7', 'Between 2 and 3 years'), ('50', 'Between 3 and 4 years'), ('58.3', 'Between 4 and 5 years'), ('66.7', 'Between 5 and 6 years'), ('75', 'Between 6 and 7 years'), ('83.3', 'Between 7 and 8 years'), ('91.7', 'Between 8 and 9 years'), ('99', 'Between 9 and 10 years')], max_length=40),
        ),
    ]
