# Generated by Django 3.2.6 on 2021-10-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0025_alter_skill_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='value',
            field=models.CharField(auto_created=True, max_length=40),
        ),
    ]
