# Generated by Django 3.2.6 on 2021-10-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0026_alter_skill_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media_page',
            name='cv',
            field=models.FileField(default='', upload_to='Home/static/Home'),
        ),
        migrations.AlterField(
            model_name='media_page',
            name='my_picture',
            field=models.ImageField(default='', upload_to='Home/static/Home/images'),
        ),
    ]
